/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import com.google.protobuf.gradle.*
import org.gradle.kotlin.dsl.provider.gradleKotlinDslOf

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.61"
    id("com.google.protobuf") version "0.8.8"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Apache Beam
    implementation("org.apache.beam:beam-sdks-java-core:2.19.0")
    implementation("org.apache.beam:beam-sdks-java-io-kafka:2.19.0")
    implementation("org.apache.beam:beam-sdks-java-io-parquet:2.19.0")
    implementation("org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.19.0")
    implementation("org.apache.beam:beam-sdks-java-extensions-protobuf:2.19.0")
    implementation("org.apache.beam:beam-runners-direct-java:2.19.0")
    implementation("org.apache.beam:beam-runners-google-cloud-dataflow-java:2.19.0")

    // Apache Kafka
    implementation("org.apache.kafka:kafka-clients:2.3.0")

    // Protobuf libraries
    implementation("com.google.protobuf:protobuf-java-util:3.11.4")

    // Logging
    implementation("org.slf4j:slf4j-api:1.6.1")
    implementation("org.slf4j:slf4j-jdk14:1.6.1")

    // Proto files to compile
    protobuf(files("ext/"))

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    applicationDefaultJvmArgs = listOf(
        "-Dexec.args=\"--runner=DirectRunner --project=trv-hs-hp-playground-test\""
    )

    mainClassName = "kafka.consumer.ConsumerKt"
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.6.1"
    }

    generateProtoTasks {
        all().forEach { task ->

        }
    }
}